### ISSUE TITLE
This is written in C++, not Python

### ISSUE THREAD

**Issue by vihaanmody1** [jtauber/cleese#4]

**Comment by stefanocoding** [comment]
Quote from the README:
> Cleese is a project to build a functioning operating system written almost
> entirely in Python. The basic idea is to have a microkernel mostly based on
> the Python VM and all other operating system functionality written in Python.

**Comment by Vihaanmody21** [comment]
![image](https://user-images.githubusercontent.com/105392905/209875749-0dadc97f-7414-4992-8f8c-d872b4d3eda3.png)

**Comment by vihaanmody1** [comment]
![image](https://user-images.githubusercontent.com/105392905/209875793-35f81f67-4b54-4080-9c98-fe87de3113df.png)

**Comment by vihaanmody1** [comment]
This barely has any python.
It is not almost everything.
It's only 2.7%

**Comment by stefanocoding** [comment]
It's an open source project. If you want it to have more Python code, you can write it and send a pull request with it.

**Comment by jtauber** [comment]
What do they expect the Python interpreter to be written in? Also it's C not C++. 

Closing this as the person is just an ignorant troll.

**Comment by vihaanmody1** [comment]
You cannot comment that to someone.
I am reporting you to Github.

![Screenshot 2023-01-03 5 26 59 PM](https://user-images.githubusercontent.com/105392905/210452754-2e6cd4ae-6d9a-4696-8d80-15b0d65cddb8.png)
